version: '3.8'

services:
  php81:
    build:
      context: .
      dockerfile: .docker/php81.Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
  php82:
    build:
      context: .
      dockerfile: .docker/php82.Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
  php83:
    build:
      context: .
      dockerfile: .docker/php83.Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
